name: Update Star Chart
on:
    push:
        paths:
            - "academia.txt" # runs when "academia.txt" is updated
    workflow_dispatch: # adds manual run capability

jobs:
    build-and-update:
        runs-on: ubuntu-latest
        permissions:
            contents: write # give write permission for this update job
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Compile C++ generator
              run: g++ staryu.cpp -o starGen
            
            - name: Generate New SVG
              run: ./starGen

            - name: Commit and Push Chart
              uses: EndBug/add-and-commit@v9
              with:
                author_name: GitHub Action
                message: "Auto-update star chart"
                add: "academia.svg"
                add: "README.md"
